//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace student_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcript
    {
        public int transcript_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<System.DateTime> generated_date { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
